# encoding: utf-8
from data_builder import terms, add

# =========================================================================
# 4. INVESTING (18 terms)
# =========================================================================
add(
    "compounding", "Compounding", "Investing",
    "The exponential growth process where investment returns generate their own subsequent earnings over multiannual holding horizons.",
    "धन वृद्धि की वह घातांकीय प्रक्रिया जिसमें निवेश से मिला मुनाफा आगे चलकर और अधिक मुनाफा पैदा करता है।",
    "गुंतवणुकीतून मिळालेला नफा पुन्हा गुंतवून त्यावरही नफा मिळवण्याची घातांकी (Exponential) संपत्ती वाढ प्रक्रिया.",
    "Planting a single mango sapling that yields fruit, whose seeds sprout into an entire thriving orchard over three decades.",
    "A monthly investment of ₹10,000 compounding at 12% CAGR yields ~₹23.2 Lakh in 10 years, jumping exponentially to ~₹99.9 Lakh in 20 years and ~₹3.5 Crore in 30 years.",
    "Time in the market is vastly more powerful than timing the market; starting 5 years earlier can double your ultimate retirement corpus.",
    "चक्रवृद्धि में समय सबसे महत्वपूर्ण घटक है; 5 साल पहले निवेश शुरू करना आपके रिटायरमेंट फंड को दोगुना कर सकता है।",
    "चक्रवाढीच्या जादूमध्ये वेळेला सर्वात जास्त महत्त्व असते; ५ वर्षे आधी सुरू केल्यास निवृत्तीचा निधी दुप्पट होऊ शकतो.",
    "Interrupting compound growth by redeeming equity portfolios during routine market corrections rather than staying invested.",
    "बाजार के सामान्य उतार-चढ़ाव में घबराकर इक्विटी निवेश को बार-बार बेचना और कंपाउंडिंग की प्रक्रिया को तोड़ना।",
    "बाजारातील तात्पुरत्या घसरणीला घाबरून गुंतवणूक काढून घेणे आणि चक्रवाढीची साखळी खंडित करणे.",
    "Compounding delivers massive dramatic wealth gains in the very first 12 to 24 months of starting an investment.",
    "चक्रवृद्धि का जादुई असर निवेश शुरू करने के पहले ही 1-2 वर्षों में भारी मुनाफे के रूप में दिखने लगता है।",
    "गुंतवणूक सुरू केल्यावर पहिल्याच वर्षात चक्रवाढ व्याजाचा प्रचंड मोठा परतावा दिसू लागतो.",
    ["Students & Freshers", "Salaried Employees", "Startup Founders"],
    {"searchFallback": "https://www.youtube.com/results?search_query=Power+of+Compounding+wealth+creation+English", "title": "The Eighth Wonder: Power of Compounding", "channel": "Zerodha Varsity"},
    {"searchFallback": "https://www.youtube.com/results?search_query=Compounding+ki+shakti+Hindi+video", "title": "कंपाउंडिंग की शक्ति: 10,000 से करोड़ों का सफर", "channel": "Pranjal Kamra"},
    {"searchFallback": "https://www.youtube.com/results?search_query=Chakravadh+gupt+shakti+Marathi", "title": "चक्रवाढ व्याजाची खरी ताकद मराठी", "channel": "CA Rachana Ranade Marathi"}
)

add(
    "sip", "SIP (Systematic Investment Plan)", "Investing",
    "A disciplined automated investment mechanism allocating a fixed rupee installment periodically into a mutual fund scheme, harnessing Rupee Cost Averaging.",
    "म्यूचुअल फंड में निश्चित अंतराल पर एक तय राशि निवेश करने की अनुशासित स्वचालित प्रणाली, जो बाजार में औसत खरीद लागत का लाभ देती है।",
    "म्युच्युअल फंडामध्ये दरमहा ठराविक रक्कम शिस्तबद्ध पद्धतीने गुंतवण्याची स्वयंचलित पद्धत, ज्यामुळे सरासरी खरेदी किमतीचा (Rupee Cost Averaging) मोठा फायदा मिळतो.",
    "An automated savings deposit paid to your future self every month before lifestyle spending commences.",
    "Investing ₹5,000 monthly through an automated SIP in a Nifty 50 Index Fund buys more units during market corrections and fewer during peaks.",
    "Never pause or cancel active SIPs during bear markets; market downturns are precisely when your SIP accumulates maximum units at discounted valuations.",
    "शेयर बाजार गिरने पर कभी भी अपनी SIP बंद न करें; मंदी के समय ही SIP सबसे सस्ती कीमत पर अधिकतम यूनिट्स खरीदती है।",
    "बाजार घसरल्यावर कधीही SIP थांबवू नका; बाजार खाली असतानाच SIP द्वारे सर्वात जास्त युनिट्स स्वस्तात जमा होतात.",
    "Attempting to manually time the market by stopping SIPs at market peaks and trying to restart at market bottoms.",
    "बाजार का अनुमान लगाने की कोशिश में SIP रोकना और फिर बाजार भाग जाने पर ऊंचे स्तर पर दोबारा निवेश करना।",
    "बाजार खाली पडल्यावर घाबरून SIP बंद करणे आणि तेजी आल्यावर पुन्हा महाग भावात सुरू करणे.",
    "SIP is a separate, government-guaranteed asset class that guarantees fixed positive annual returns regardless of market performance.",
    "SIP एक अलग सरकारी गारंटी वाली संपत्ति है जो बाजार गिरने पर भी निश्चित सकारात्मक रिटर्न की गारंटी देती है।",
    "SIP हा एक स्वतंत्र सरकारी योजना असून बाजारातील चढ-उतारांशी त्याचा कसलाही संबंध नसतो.",
    ["Salaried Employees", "Students & Freshers", "Freelancers & Creators"],
    {"videoId": "t6BQ1Wle8c4", "searchFallback": "https://www.youtube.com/results?search_query=SIP+Systematic+Investment+Plan+guide+English", "title": "Lumpsum or SIP, Which is Better?", "channel": "CA Rachana Phadke Ranade"},
    {"videoId": "fLqdzG7vtps", "searchFallback": "https://www.youtube.com/results?search_query=SIP+kya+hai+kaise+shuru+kare+Hindi", "title": "SIP for Beginners: What Is SIP", "channel": "Bajaj Finserv Mutual Fund"},
    {"videoId": "nnj3GFOJeKM", "searchFallback": "https://www.youtube.com/results?search_query=SIP+Marathi+margdarshan", "title": "SIP मध्ये गुंतवणूक करण्याचे नियम मराठी", "channel": "CA Rachana Ranade Marathi"}
)

add(
    "mutual-funds", "Mutual Funds", "Investing",
    "A collective investment vehicle pooling capital from retail and institutional investors to construct a professionally managed diversified portfolio of securities.",
    "कई निवेशकों से पूंजी एकत्र कर पेशेवर फंड मैनेजरों द्वारा शेयरों, बॉन्डों और प्रतिभूतियों के विविधीकृत पोर्टफोलियो में निवेश करने का माध्यम।",
    "अनेक गुंतवणूकदारांचे पैसे एकत्र करून व्यावसायिक फंड मॅनेजरद्वारे समभाग आणि रोख्यांच्या विविधीकृत पोर्टफोलिओमध्ये केलेली गुंतवणूक.",
    "Hiring a seasoned ship captain with a professional crew to navigate the turbulent ocean of markets rather than rowing a fragile solo boat.",
    "Regulated stringently by SEBI under the Mutual Fund Regulations 1996, with assets held by independent statutory custodians.",
    "Select Direct Plans of mutual funds instead of Regular Plans to eliminate distributor commissions and save 0.5%–1.2% in annual expense ratios.",
    "म्यूचुअल फंड में हमेशा 'Direct Plan' चुनें ताकि एजेंट कमीशन न लगे और आपका वार्षिक रिटर्न 1% तक बढ़ सके।",
    "म्युच्युअल फंडामध्ये नेहमी 'Direct Plan' ची निवड करा, ज्यामुळे कमिशन वाचून वार्षिक परतावा वाढतो.",
    "Investing in dozens of overlapping mutual funds holding the exact same underlying large-cap equities.",
    "एक ही श्रेणी के 10-15 म्यूचुअल फंड खरीद लेना जिनमें अंदरूनी तौर पर वही समान शेयर शामिल होते हैं।",
    "एकाच प्रकारच्या अनेक म्युच्युअल फंडात गुंतवणूक करणे, ज्यामुळे विविधीकरण न होता केवळ गोंधळ वाढतो.",
    "Investing in mutual funds is equivalent to gambling in speculative lottery tickets with zero regulatory oversight.",
    "म्यूचुअल फंड में निवेश करना सट्टेबाजी जैसा है और इस पर सरकार या सेबी का कोई नियंत्रण नहीं होता।",
    "म्युच्युअल फंडात गुंतवणूक करणे म्हणजे कसलेही नियम नसलेला जुगार खेळण्यासारखे आहे.",
    ["Salaried Employees", "Students & Freshers", "Freelancers & Creators"],
    {"searchFallback": "https://www.youtube.com/results?search_query=Mutual+Funds+complete+guide+for+beginners+English", "title": "Mutual Funds Complete Beginner's Guide", "channel": "Zerodha Varsity"},
    {"searchFallback": "https://www.youtube.com/results?search_query=Mutual+fund+kya+hai+Hindi+video", "title": "म्यूचुअल फंड क्या है और सही फंड कैसे चुनें?", "channel": "Pranjal Kamra"},
    {"videoId": "5Ls-mm01SdA", "searchFallback": "https://www.youtube.com/results?search_query=Mutual+funds+Marathi+mahiti", "title": "What are Mutual Funds? म्युच्युअल फंडस् म्हणजे काय?", "channel": "CA Rachana Ranade Marathi"}
)

add(
    "equity", "Equity (Stock Ownership)", "Investing",
    "A fractional ownership share in the capital of a corporation, entitling the shareholder to voting rights, corporate earnings, and long-term capital appreciation.",
    "किसी कंपनी के पूंजीगत स्वामित्व का आनुपातिक हिस्सा, जो शेयरधारक को कंपनी के मुनाफे (डिविडेंड) और दीर्घकालिक पूंजीगत वृद्धि का अधिकार देता है।",
    "एखाद्या कंपनीच्या भांडवलातील प्रत्यक्ष मालकीचा हिस्सा (शेअर); जो नफ्यातील लाभांश आणि भांडवली मूल्याच्या वाढीचा हक्क प्रदान करतो.",
    "Holding a registered ownership title deed to a percentage of a commercial shopping complex that earns rental distributions and appreciates in market value.",
    "Historical Nifty 50 and S&P BSE Sensex indices have compounded at ~12%–14% annualized over multi-decade intervals, outperforming inflation and fixed income.",
    "Equity represents real ownership in productive business enterprises, not an arbitrary fluctuating ticker on a smartphone screen.",
    "इक्विटी को फोन स्क्रीन पर नाचते हुए अंकों के रूप में नहीं, बल्कि वास्तविक व्यवसायों की आंशिक साझेदारी के रूप में देखें।",
    "इक्विटी म्हणजे फोनवरील आकडे नसून देशातील नफा कमावणाऱ्या खऱ्याखुऱ्या व्यवसायांमधील मालकी हक्क आहे.",
    "Treating equity markets like a fast-paced day-trading casino rather than taking a 5-to-10 year ownership perspective.",
    "शेयर बाजार को लॉटरी समझकर इंट्राडे ट्रेडिंग करना और कुछ ही हफ्तों में अपनी गाढ़ी कमाई गंवा बैठना।",
    "शेअर बाजारात जलद नफा मिळवण्याच्या हव्यासापोटी ट्रेडिंग करणे आणि मूळ भांडवल गमावून बसणे.",
    "Equities are guaranteed to decline in purchasing power over any arbitrary 20-year horizon in modern economies.",
    "लंबी अवधि (15-20 साल) में भी शेयर बाजार हमेशा सोने या एफडी से कम ही रिटर्न देता है।",
    "दीर्घकालीन विचार केल्यास समभाग नेहमी बँक ठेवींपेक्षा कमी परतावा देतात असा समज.",
    ["Salaried Employees", "Startup Founders", "Freelancers & Creators"],
    {"searchFallback": "https://www.youtube.com/results?search_query=What+is+Equity+stock+market+basics+English", "title": "Equity & Stock Market Fundamentals", "channel": "Zerodha Varsity"},
    {"videoId": "RieqxXMds64", "searchFallback": "https://www.youtube.com/results?search_query=Share+market+basics+Hindi", "title": "Stock Market Basics for Beginners", "channel": "Pranjal Kamra"},
    {"searchFallback": "https://www.youtube.com/results?search_query=Share+market+Marathi+margdarshan", "title": "शेअर मार्केट म्हणजे काय? सोपी मराठी माहिती", "channel": "Groww Marathi"}
)

add(
    "diversification", "Diversification", "Investing",
    "The risk-management technique of allocating capital across diverse asset classes, industrial sectors, and geographical markets to minimize unsystematic volatility.",
    "पूंजी को विभिन्न परिसंपत्तियों (शेयर, डेट, सोना, रियल एस्टेट) और उद्योगों में बांटने की रणनीति, ताकि किसी एक क्षेत्र के नुकसान से पूरा पोर्टफोलियो सुरक्षित रहे।",
    "आपले भांडवल केवळ एकाच ठिकाणी न ठेवता समभाग, रोखे, सोने आणि स्थावर मालमत्ता अशा विविध पर्यायांमध्ये विभागून जोखीम कमी करण्याचे तंत्र.",
    "Carrying your farm harvest in multiple sturdy baskets so dropping one container does not destroy your entire year's crop.",
    "A classic multi-asset allocation comprising 60% Domestic Equity, 20% Debt/Fixed Income, 10% Gold, and 10% International Equity cushions severe drawdown shocks.",
    "Diversification is the only genuine 'free lunch' in modern finance, enabling higher risk-adjusted returns with significantly lower drawdown anxiety.",
    "विविधीकरण (Diversification) वित्तीय जगत का एकमात्र 'मुफ्त उपहार' है जो जोखिम को घटाते हुए पोर्टफोलियो के रिटर्न को स्थिर बनाता है।",
    "विविधीकरण हे गुंतवणुकीतील सर्वात मोठे सुरक्षा कवच आहे, ज्यामुळे बाजारातील घसरणीतही संपत्ती सुरक्षित राहते.",
    "Over-diversification across 50 different equity mutual funds holding identical underlying stocks, creating administrative confusion with zero extra benefit.",
    "50 अलग-अलग म्यूचुअल फंड खरीद लेना जिससे वास्तविक विविधीकरण नहीं बल्कि केवल अव्यवस्था और शुल्क बढ़ते हैं।",
    "अवाजवी विविधीकरण करून ५० वेगवेगळ्या फंडांमध्ये पैसे गुंतवणे, ज्यामुळे कसलाही अतिरिक्त लाभ मिळत नाही.",
    "True diversification means buying 10 different banking stocks listed within the identical domestic financial sub-sector.",
    "केवल 10 अलग-अलग बैंकों के शेयर खरीद लेना संपूर्ण पोर्टफोलियो विविधीकरण कहलाता है।",
    "केवळ एकाच क्षेत्रातील (उदा. बँक) ५-६ कंपन्यांचे शेअर्स घेणे म्हणजे संपूर्ण विविधीकरण नव्हे.",
    ["Salaried Employees", "Students & Freshers", "Startup Founders"],
    {"searchFallback": "https://www.youtube.com/results?search_query=Asset+allocation+and+diversification+rules+English", "title": "The Art of Portfolio Diversification", "channel": "Zerodha Varsity"},
    {"searchFallback": "https://www.youtube.com/results?search_query=Diversification+kaise+kare+Hindi", "title": "पोर्टफोलियो विविधीकरण कैसे करें? सही तरीका", "channel": "Asset Yogi"},
    {"searchFallback": "https://www.youtube.com/results?search_query=Vividhikaran+guntavnuk+Marathi", "title": "गुंतवणुकीचे योग्य विविधीकरण कसे करावे? मराठी", "channel": "Groww Marathi"}
)

add(
    "risk-return", "Risk-Return Tradeoff", "Investing",
    "The fundamental financial principle stating that the potential reward on an investment scales in direct proportion to the level of capital risk accepted.",
    "वित्तीय बाजार का मूल सिद्धांत कि किसी निवेश में अधिक मुनाफे की संभावना के साथ मूलधन खोने का संभावित जोखिम भी सीधे अनुपात में बढ़ता है।",
    "गुंतवणुकीतील मूलभूत तत्त्व: संभाव्य परतावा जितका जास्त असेल, तितकीच भांडवली नुकसानीची जोखीमही जास्त असते.",
    "Driving at 140 km/h reaches your destination faster, but demands superior braking reflexes and carries greater accident severity than cruising at 60 km/h.",
    "Equities offer 12%–15% long-term return potential but carry 20%–30% interim drawdown risk; Bank FDs offer 7% fixed return with zero nominal drawdown risk.",
    "Any unregulated investment scheme offering 'guaranteed 20%–30% monthly returns' is statistically guaranteed to be an illegal Ponzi fraud.",
    "कोई भी योजना जो 'गारंटीड 20%-30% रिटर्न' का वादा करे, वह निश्चित रूप से एक अवैध पोंजी घोटाला है; लालच से बचें।",
    "दरमहा 'निश्चित २०%-३०% परतावा' देण्याचा दावा करणारी कोणतीही योजना हमखास फसवणूक (Ponzi Scam) असते; अशा भूलथापांना बळी पडू नका.",
    "Assuming that low risk equates to zero risk, ignoring how inflation silently destroys the real purchasing power of 'safe' cash under the mattress.",
    "यह मान लेना कि सुरक्षित बचत में कोई जोखिम नहीं है, जबकि महंगाई चुपचाप पैसे की क्रय शक्ति को खा जाती है।",
    "पैसा केवळ बचत खात्यात ठेवून सुरक्षित राहू शकतो असा समज, महागाई हळूहळू पैशाचे मूल्य संपवते याकडे दुर्लक्ष करणे.",
    "There exist special secret financial instruments that consistently yield 25% annual risk-free returns backed by sovereign guarantees.",
    "बाजार में ऐसे जादुई वित्तीय प्रोडक्ट मौजूद हैं जो बिना किसी जोखिम के 25% का निश्चित वार्षिक रिटर्न देते हैं।",
    "बाजारात कसलीही जोखीम नसताना निश्चित २५% परतावा देणारी गुप्त सरकारी योजना अस्तित्वात असते असा गैरसमज.",
    ["Students & Freshers", "Salaried Employees"],
    {"searchFallback": "https://www.youtube.com/results?search_query=Risk+Return+Tradeoff+in+investing+English", "title": "Understanding the Risk-Return Spectrum", "channel": "Finnovate"},
    {"searchFallback": "https://www.youtube.com/results?search_query=Risk+aur+return+ka+khel+Hindi", "title": "Risk और Return का असली खेल समझें", "channel": "Pranjal Kamra"},
    {"searchFallback": "https://www.youtube.com/results?search_query=Jokhim+ani+partava+Marathi", "title": "गुंतवणुकीतील जोखीम आणि परतावा मराठी", "channel": "CA Rachana Ranade Marathi"}
)

add(
    "index-fund", "Index Fund (Passive Investing)", "Investing",
    "A passive mutual fund designed to replicate the composition and match the performance of a financial benchmark index like the Nifty 50 or S&P BSE Sensex.",
    "एक निष्क्रिय म्यूचुअल फंड जो निफ्टी 50 या सेंसेक्स जैसे बेंचमार्क इंडेक्स के शेयरों और उनके अनुपात की हूबहू नकल करता है।",
    "निफ्टी ५० किंवा सेन्सेक्स यांसारख्या निर्देशांकांची हुबेहूब नक्कल करून अत्यंत कमी खर्चात परतावा देणारा पॅसिव्ह म्युच्युअल फंड.",
    "Buying a basket containing all 50 premiere players on the national cricket leaderboard instead of gambling on betting who will score a century today.",
    "Nifty 50 Index funds feature rock-bottom expense ratios (0.05%–0.20%) and zero fund manager bias, beating over 75% of actively managed funds over 10-year periods.",
    "For the vast majority of retail investors, an automated low-cost Nifty 50 Index Fund SIP is the single most reliable path to multi-decade wealth creation.",
    "अधिकांश सामान्य निवेशकों के लिए निफ्टी 50 इंडेक्स फंड में निरंतर SIP वेल्थ क्रिएशन का सबसे सुरक्षित और प्रभावी मार्ग है।",
    "सामान्य नोकरदार गुंतवणूकदारांसाठी निफ्टी ५० इंडेक्स फंडामधील मासिक SIP हा संपत्ती निर्मितीचा सर्वात सोपा आणि खात्रीशीर मार्ग आहे.",
    "Switching out of index funds after a short-term market dip in search of fashionable 'hot' thematic sector funds that subsequently crash.",
    "अस्थायी मंदी में इंडेक्स फंड बंद करके किसी ट्रेंडिंग सेक्टोरल फंड में भागना और फिर उसमें भारी नुकसान उठाना।",
    "बाजार खाली आल्यावर इंडेक्स फंडातून पैसे काढून धोकादायक सेक्टरल फंडात टाकणे आणि नुकसान करून घेणे.",
    "Index funds carry active fund manager intervention to sell declining stocks and pick upcoming multi-baggers manually.",
    "इंडेक्स फंड के मैनेजर हर हफ्ते अपनी मर्जी से खराब शेयर हटाते हैं और नए शेयर जोड़ते हैं।",
    "इंडेक्स फंड मॅनेजर स्वतःच्या मर्जीने शेअर्सची खरेदी-विक्री करतो.",
    ["Salaried Employees", "Students & Freshers"],
    {"searchFallback": "https://www.youtube.com/results?search_query=Index+funds+passive+investing+guide+India+English", "title": "Why Index Funds Win Over the Long Term", "channel": "Zerodha Varsity"},
    {"searchFallback": "https://www.youtube.com/results?search_query=Index+funds+kya+hote+hai+Hindi", "title": "Index Fund क्या है और इसमें निवेश कैसे करें?", "channel": "Pranjal Kamra"},
    {"searchFallback": "https://www.youtube.com/results?search_query=Index+fund+Marathi+mahiti", "title": "इंडेक्स फंड म्हणजे काय? मराठी माहिती", "channel": "Groww Marathi"}
)

add(
    "etf", "ETF (Exchange Traded Fund)", "Investing",
    "An investment fund holding an underlying basket of securities traded intraday on stock exchanges (NSE/BSE) at live real-time market prices.",
    "स्टॉक एक्सचेंजों (NSE/BSE) पर शेयरों की तरह दिन के दौरान लाइव कीमतों पर खरीदे और बेचे जाने वाले इंडेक्स फंड।",
    "शेअर बाजारात (NSE/BSE) नियमित समभागांप्रमाणे थेट आणि चालू भावात खरेदी-विक्री करता येणारा ओपन-एंडेड फंड.",
    "Buying an entire pre-packaged fruit platter on the supermarket shelf with one swipe at live spot prices rather than waiting for evening delivery.",
    "Popular Indian ETFs include NIFTYBEES (Nifty 50), GOLDBEES (Sovereign Gold), and LIQUIDBEES, accessible directly via Demat accounts with sub-0.10% expense ratios.",
    "When trading ETFs, always verify market depth and use limit orders to avoid paying unexpected tracking error spreads against fair NAV.",
    "ETF खरीदते समय हमेशा 'Limit Order' लगाएं ताकि मार्केट की बिड-आस्क स्प्रेड के कारण अधिक कीमत न चुकानी पड़े।",
    "ETF खरेदी करताना नेहमी 'Limit Order' चा वापर करा जेणेकरून अनाठायी जास्त भाव दिला जाणार नाही.",
    "Confusing the ETF market trading price on the stock terminal with the actual intraday Net Asset Value (iNAV).",
    "ट्रेडिंग स्क्रीन पर दिख रहे भाव को ही वास्तविक NAV मान लेना और लिक्विडिटी कम होने पर प्रीमियम चुका देना।",
    "ETF चा प्रत्यक्ष NAV न तपासता केवळ स्क्रीनवरील भावावर खरेदी करणे आणि अवाजवी प्रीमियम भरणे.",
    "ETFs require you to commit to a mandatory 3-year lock-in period before selling units on the exchange.",
    "ETF में खरीदे गए यूनिट्स को बेचने से पहले 3 साल तक रखना कानूनी रूप से अनिवार्य होता है।",
    "ETF शेअर्स विकण्यापूर्वी किमान ३ वर्षे थांबावेच लागते असा गैरसमज.",
    ["Salaried Employees", "Freelancers & Creators"],
    {"searchFallback": "https://www.youtube.com/results?search_query=ETF+vs+Mutual+Fund+differences+English", "title": "Exchange Traded Funds (ETFs) vs Mutual Funds", "channel": "Zerodha Varsity"},
    {"searchFallback": "https://www.youtube.com/results?search_query=ETF+kya+hota+hai+Hindi+video", "title": "ETF क्या है? NIFTYBEES और Gold ETF का सच", "channel": "Asset Yogi"},
    {"searchFallback": "https://www.youtube.com/results?search_query=ETF+mhanje+kay+Marathi", "title": "ETF म्हणजे काय? शेअर्सप्रमाणे गुंतवणूक मराठी", "channel": "CA Rachana Ranade Marathi"}
)

add(
    "bonds", "Bonds & Sovereign Debt", "Investing",
    "Fixed-income debt instruments where an investor loans capital to a government entity or corporation in exchange for periodic coupon interest and principal return at maturity.",
    "एक निश्चित आय साधन जिसके तहत निवेशक सरकार या कंपनी को ऋण देता है और बदले में नियमित कूपन ब्याज और परिपक्वता पर मूलधन प्राप्त करता है।",
    "गुंतवणूकदाराने सरकारला किंवा नामांकित कंपनीला दिलेले कर्ज; ज्यावर ठराविक मुदतीत नियमित व्याज (Coupon) आणि शेवटी मुद्दल परत मिळते.",
    "An official promissory IOU issued by an enterprise or the sovereign republic promising to service your capital with disciplined interest.",
    "Government of India Dated Securities (G-Secs) and State Development Loans (SDLs) carry zero sovereign credit risk and can be bought directly on RBI Retail Direct.",
    "Bonds provide essential stability and steady cash flow to counterbalance equity market volatility in retirement portfolios.",
    "बॉन्ड आपके पोर्टफोलियो को स्थिरता प्रदान करते हैं और रिटायरमेंट के बाद सुरक्षित नियमित आय का साधन बनते हैं।",
    "रोखे (Bonds) तुमच्या पोर्टफोलिओला स्थिरता देतात आणि निवृत्तीनंतर नियमित उत्पन्न मिळवून देण्यास मदत करतात.",
    "Investing in unrated or junk-rated corporate bonds offering 14% yield without assessing the severe risk of corporate default.",
    "अत्यधिक ब्याज के लालच में कमजोर रेटिंग वाले असुरक्षित कॉरपोरेट बॉन्ड्स में पैसा लगाना और मूलधन गंवा देना।",
    "जास्त व्याजाच्या मोहापायी निकृष्ट रेटिंग असणाऱ्या खाजगी बॉण्ड्समध्ये पैसे गुंतवणे आणि मुद्दल बुडवून घेणे.",
    "Corporate company bonds carry the identical 100% sovereign default guarantee as Government of India treasury bills.",
    "निजी कंपनियों के बॉन्ड्स पर भी भारत सरकार की 100% संप्रभु गारंटी लागू होती है।",
    "खाजगी कंपन्यांच्या रोख्यांनाही भारत सरकारची संपूर्ण हमी असते असा समज.",
    ["Salaried Employees", "Freelancers & Creators"],
    {"searchFallback": "https://www.youtube.com/results?search_query=Bonds+and+G+Secs+RBI+Retail+direct+English", "title": "How to Invest in Government Bonds & G-Secs", "channel": "ClearTax"},
    {"searchFallback": "https://www.youtube.com/results?search_query=Bonds+kya+hote+hai+Hindi+guide", "title": "Bonds क्या हैं और RBI Retail Direct से कैसे खरीदें?", "channel": "Pranjal Kamra"},
    {"searchFallback": "https://www.youtube.com/results?search_query=Sarkari+bonds+guntavnuk+Marathi", "title": "सरकारी रोखे (Bonds) मध्ये गुंतवणूक कशी करावी? मराठी", "channel": "Groww Marathi"}
)

add(
    "fixed-deposit", "Fixed Deposit (FD)", "Investing",
    "A term deposit held with a banking institution for a predetermined duration at a guaranteed nominal rate of interest, protected up to ₹5 Lakh under DICGC insurance.",
    "एक निश्चित अवधि के लिए बैंक में जमा की गई राशि, जिस पर निश्चित ब्याज मिलता है और जो DICGC द्वारा ₹5 लाख तक कानूनी रूप से बीमित होती है।",
    "बँकेत ठराविक मुदतीसाठी ठेवलेली रक्कम; ज्यावर निश्चित व्याज मिळते आणि DICGC कायद्यानुसार ₹५ लाखांपर्यंत पूर्ण सरकारी विमा संरक्षण असते.",
    "A locked personal safe deposit inside a scheduled commercial bank guaranteeing your principal returns intact on the specified date.",
    "Deposit Insurance and Credit Guarantee Corporation (DICGC) insures bank deposits up to ₹5,00,000 per depositor per bank across principal and interest.",
    "Fixed deposits are superior instruments for short-term liquidity goals (under 3 years) and emergency buffers, but suboptimal for multi-decade retirement compounding.",
    "FD का उपयोग 1 से 3 साल के छोटे लक्ष्यों और आपातकालीन निधि के लिए करें, 20 साल के रिटायरमेंट फंड के लिए नहीं।",
    "FD चा वापर केवळ पुढील १ ते ३ वर्षांच्या लहान उद्दिष्टांसाठी आणि आणीबाणीच्या निधीसाठी करावा, २० वर्षांच्या निवृत्ती निधीसाठी नव्हे.",
    "Accumulating all multi-decade savings in FDs while in the 30% tax slab, where a 7% nominal return yields just ~4.9% post-tax, trailing Indian inflation.",
    "30% टैक्स स्लैब में रहकर 20 साल के लिए सारा पैसा FD में रखना, जहां टैक्स के बाद रिटर्न महंगाई से भी कम रह जाता है।",
    "सर्व पैसे अनेक वर्षांसाठी केवळ FD मध्ये ठेवणे, जिथे कर वजा जाता मिळणारा परतावा महागाईपेक्षाही कमी पडतो.",
    "If a commercial bank fails, all deposits exceeding ₹5 Lakh are automatically settled by the RBI within 48 hours without limit.",
    "बैंक दिवालिया होने पर ₹5 लाख से अधिक की पूरी जमा राशि भी RBI द्वारा 48 घंटे में तुरंत चुका दी जाती है।",
    "बँक बुडाली तरी ₹५ लाखांच्या वरील संपूर्ण रक्कम RBI कडून लगेच दिली जाते असा गैरसमज.",
    ["Salaried Employees", "Students & Freshers"],
    {"searchFallback": "https://www.youtube.com/results?search_query=Bank+FD+vs+Debt+Mutual+Funds+taxation+English", "title": "Bank Fixed Deposits vs Inflation Reality", "channel": "Finnovate"},
    {"searchFallback": "https://www.youtube.com/results?search_query=Bank+FD+me+kitna+risk+hai+Hindi", "title": "Bank FD का सच: ₹5 लाख बीमा और टैक्स", "channel": "Labor Law Advisor"},
    {"searchFallback": "https://www.youtube.com/results?search_query=Bank+FD+fayde+tote+Marathi", "title": "बँक FD आणि DICGC ५ लाख विमा संरक्षण मराठी", "channel": "CA Rachana Ranade Marathi"}
)

add(
    "ppf", "PPF (Public Provident Fund)", "Investing",
    "A 15-year statutory central government savings scheme offering complete Exempt-Exempt-Exempt (EEE) tax-free status on contributions, interest, and maturity proceeds.",
    "15-वर्षीय केंद्रीय सरकारी बचत योजना, जो निवेश, ब्याज और परिपक्वता तीनों चरणों पर पूर्ण कर-मुक्त (EEE) लाभ प्रदान करती है।",
    "केंद्र सरकारची १५ वर्षांची सुरक्षित बचत योजना; ज्यावर गुंतवणूक, मिळालेले व्याज आणि अंतिम मुदतपूर्ती रक्कम हे तिन्ही टप्पे पूर्णपणे करमुक्त (EEE) असतात.",
    "A sovereign titanium vault that shields your family capital from income tax levies, economic volatility, and even legal attachment.",
    "Currently offers ~7.1% government-set interest compounding annually. Balances in a PPF account cannot be attached by any court decree under the PPF Act.",
    "Deposit your annual PPF contribution between the 1st and 5th of April each year to maximize full 12 months of compounded interest for that financial year.",
    "अधिकतम ब्याज कमाने के लिए हर वित्तीय वर्ष में अपना PPF अंशदान हमेशा 1 से 5 अप्रैल के बीच जमा करें।",
    "वर्षाचे जास्तीत जास्त व्याज मिळवण्यासाठी दरवर्षी १ ते ५ एप्रिलच्या दरम्यानच PPF चे पैसे खात्यात भरावेत.",
    "Depositing funds into PPF after the 5th of the month and losing that entire month's interest calculation.",
    "महीने की 5 तारीख के बाद पैसा जमा करना, जिससे उस पूरे महीने का ब्याज शून्य हो जाता है।",
    "महिन्याच्या ५ तारखेनंतर पैसे जमा करणे, ज्यामुळे त्या संपूर्ण महिन्याचे व्याज मिळत नाही.",
    "You are legally permitted to open multiple personal PPF accounts in different bank branches across India.",
    "एक व्यक्ति भारत भर में विभिन्न बैंकों में अपने नाम से कई अलग-अलग PPF खाते खोल सकता है।",
    "एका व्यक्तीला स्वतःच्या नावे वेगवेगळ्या बँकांमध्ये अनेक PPF खाती उघडण्याची परवानगी असते.",
    ["Salaried Employees", "Freelancers & Creators", "Students & Freshers"],
    {"searchFallback": "https://www.youtube.com/results?search_query=Public+Provident+Fund+PPF+rules+and+interest+English", "title": "Public Provident Fund (PPF) Mastery Guide", "channel": "ClearTax"},
    {"searchFallback": "https://www.youtube.com/results?search_query=PPF+account+ke+fayde+Hindi", "title": "PPF Account के नियम और 5 अप्रैल की ट्रिक", "channel": "Asset Yogi"},
    {"searchFallback": "https://www.youtube.com/results?search_query=PPF+yojana+Marathi+mahiti", "title": "PPF सार्वजनिक भविष्य निर्वाह निधी मराठी", "channel": "Groww Marathi"}
)

add(
    "dividend", "Dividend (Corporate Profit Sharing)", "Investing",
    "The distribution of a portion of an enterprise's net profits directly to shareholders, approved by the company's board of directors.",
    "कंपनी द्वारा अपने शुद्ध मुनाफे का एक हिस्सा शेयरधारकों को नकद रूप में वितरित करना, जो कंपनी के निदेशक मंडल द्वारा अनुमोदित होता है।",
    "कंपनीने कमावलेल्या निव्वळ नफ्यातील काही हिस्सा भागधारकांना थेट रोख स्वरूपात वाटणे (लाभांश).",
    "A commercial fruit harvest payout delivered to every co-owner of the farm at the close of every fiscal quarter.",
    "Under current Indian tax provisions, dividends are added directly to your taxable income and taxed at your regular personal slab rate, with 10% TDS under Section 194 if exceeding ₹5,000.",
    "Reinvest dividend distributions back into the market during your wealth accumulation years to keep the compounding engine firing at peak capacity.",
    "युवावस्था में मिलने वाले सभी डिविडेंड को दोबारा निवेश करें ताकि कंपाउंडिंग की रफ्तार धीमी न पड़े।",
    "तरुण वयात मिळणारा लाभांश खर्च न करता पुन्हा बाजारात गुंतवावा, ज्यामुळे चक्रवाढ वृद्धी सुरू राहते.",
    "Selecting stocks solely based on a high headline dividend yield while ignoring collapsing company fundamentals or depleting capital value.",
    "केवल ऊंचे डिविडेंड यील्ड के चक्कर में डूबती हुई कंपनियों के शेयर खरीदना और पूंजी का भारी नुकसान कराना।",
    "केवळ जास्त लाभांश मिळतो म्हणून तोट्यात जाणाऱ्या कंपन्यांचे शेअर्स खरेदी करणे.",
    "Dividends received from listed Indian corporations are completely 100% tax-free in the hands of all retail investors.",
    "भारतीय कंपनियों से मिलने वाला डिविडेंड सभी निवेशकों के लिए पूरी तरह से कर-मुक्त होता है (2020 के बाद यह स्लैब रेट पर टैक्स होता है)।",
    "भारतीय कंपन्यांकडून मिळणारा लाभांश पूर्णपणे करमुक्त असतो असा जुना गैरसमज.",
    ["Salaried Employees", "Freelancers & Creators"],
    {"searchFallback": "https://www.youtube.com/results?search_query=Dividend+investing+and+taxation+India+English", "title": "Dividend Investing Strategy & Taxation", "channel": "Zerodha Varsity"},
    {"searchFallback": "https://www.youtube.com/results?search_query=Dividend+kya+hota+hai+Hindi+guide", "title": "डिविडेंड क्या है और इस पर टैक्स कैसे लगता है?", "channel": "Pranjal Kamra"},
    {"searchFallback": "https://www.youtube.com/results?search_query=Labhansh+dividend+Marathi", "title": "लाभांश (Dividend) म्हणजे काय? मराठी माहिती", "channel": "CA Rachana Ranade Marathi"}
)

add(
    "market-cap", "Market Capitalization", "Investing",
    "The aggregate valuation of a publicly traded company, calculated by multiplying its total outstanding shares by the prevailing market price per share.",
    "शेयर बाजार में सूचीबद्ध कंपनी का कुल बाजार मूल्य, जो उसके कुल बकाया शेयरों को प्रति शेयर मौजूदा बाजार मूल्य से गुणा करके निकाला जाता है।",
    "शेअर बाजारात नोंदणीकृत कंपनीचे एकूण बाजार भांडवल; हे एकूण शेअर्सच्या संख्येला चालू बाजारभावाने गुणून काढले जाते.",
    "The total purchase price required to buy 100% of all apartments in a massive residential skyscraper complex at current market rates.",
    "SEBI categorizes Indian stocks into: Large Cap (Top 100 companies by market cap), Mid Cap (101st to 250th), and Small Cap (251st onwards).",
    "Large caps provide portfolio resilience during bear markets, whereas mid and small caps offer higher growth potential with sharp interim volatility.",
    "स्थिरता के लिए लार्ज कैप और तेज विकास के लिए मिड व स्मॉल कैप का संतुलित मिश्रण पोर्टफोलियो में रखें।",
    "पोर्टफोलिओच्या सुरक्षिततेसाठी लार्ज कॅप आणि जलद वाढीसाठी मिड व स्मॉल कॅप शेअर्सचा योग्य समतोल ठेवावा.",
    "Assuming that a stock priced at ₹10 is 'cheap' compared to a stock priced at ₹3,000 without looking at the total market capitalization and shares outstanding.",
    "₹10 के शेयर को 'सस्ता' और ₹3000 के शेयर को 'महंगा' मान लेना, बिना कंपनी का कुल मार्केट कैप देखे।",
    "शेअरचा भाव ₹१० आहे म्हणून तो स्वस्त आणि ₹३००० आहे म्हणून महाग असा भाबडा हिशोब करणे.",
    "Small-cap companies carry identical business stability and downside protection as established blue-chip large-cap corporations.",
    "स्मॉल-कैप कंपनियों में भी लार्ज-कैप कंपनियों जैसी ही आर्थिक स्थिरता और सुरक्षा होती है।",
    "लहान कंपन्यांमध्ये (Small Cap) मोठ्या कंपन्यांइतकीच आर्थिक स्थिरता असते असा गैरसमज.",
    ["Salaried Employees", "Students & Freshers"],
    {"searchFallback": "https://www.youtube.com/results?search_query=Large+Cap+Mid+Cap+Small+Cap+explained+English", "title": "Market Capitalization: Large vs Mid vs Small Cap", "channel": "Zerodha Varsity"},
    {"searchFallback": "https://www.youtube.com/results?search_query=Market+cap+kya+hota+hai+Hindi", "title": "Market Cap क्या है? सही शेयर कैसे चुनें?", "channel": "Asset Yogi"},
    {"searchFallback": "https://www.youtube.com/results?search_query=Bajar+bhandval+market+cap+Marathi", "title": "मार्केट कॅपिटलायझेशन म्हणजे काय? मराठी", "channel": "Groww Marathi"}
)

add(
    "ipo", "IPO (Initial Public Offering)", "Investing",
    "The formal statutory process by which a privately held enterprise issues new or existing equity shares to the public for the first time on stock exchanges.",
    "वह प्रक्रिया जिसके तहत कोई निजी कंपनी पहली बार आम जनता को शेयर जारी कर स्टॉक एक्सचेंजों पर सूचीबद्ध होती है।",
    "एखादी खाजगी कंपनी पहिल्यांदाच सर्वसामान्य जनतेला आपले शेअर्स विक्रीसाठी उपलब्ध करून शेअर बाजारात नोंदणीकृत होण्याची अधिकृत प्रक्रिया.",
    "A private boutique bakery opening its doors to public franchise co-owners nationwide for the first time.",
    "Governed by SEBI Issue of Capital and Disclosure Requirements (ICDR) Regulations, with retail investors applying via UPI ASBA mandates through their bank or broker.",
    "Do not apply for IPOs solely based on unverified grey market premium (GMP) hype; scrutinize the company's valuation, debt levels, and promoter governance in the Red Herring Prospectus (RHP).",
    "केवल ग्रे मार्केट प्रीमियम (GMP) के झांसे में आकर IPO में पैसा न लगाएं; कंपनी का वास्तविक वित्तीय विवरण और मूल्यांकन जांचें।",
    "केवळ ग्रे मार्केटच्या (GMP) अफवांवर विश्वास ठेवून IPO मध्ये पैसे गुंतवू नका; कंपनीचा ताळेबंद आणि नफा नीट तपासा.",
    "Flipping for one-day listing gains and borrowing money at high interest to apply for oversubscribed retail tranches.",
    "लिस्टिंग गेन के लालच में भारी ब्याज पर कर्ज लेकर IPO में बोली लगाना और घाटा उठाना।",
    "लिस्टिंगच्या दिवशी नफा कमावण्याच्या हव्यासापोटी व्याजाने उसने पैसे काढून IPO मध्ये अर्ज करणे.",
    "Every IPO that lists on the NSE or BSE is guaranteed to open at a positive premium above its issue price.",
    "शेयर बाजार में आने वाला हर IPO अनिवार्य रूप से अपने निर्गम मूल्य से ऊपर प्रीमियम पर ही लिस्ट होता है।",
    "शेअर बाजारात येणारा प्रत्येक IPO हा निश्चितपणे नफ्यातच लिस्ट होतो असा समज.",
    ["Salaried Employees", "Freelancers & Creators", "Startup Founders"],
    {"searchFallback": "https://www.youtube.com/results?search_query=How+IPOs+work+how+to+apply+ASBA+English", "title": "How IPOs Work: Red Herring Prospectus to Listing", "channel": "Zerodha Varsity"},
    {"searchFallback": "https://www.youtube.com/results?search_query=IPO+kya+hota+hai+Hindi+video", "title": "IPO क्या होता है और इसमें अप्लाई कैसे करें?", "channel": "Pranjal Kamra"},
    {"searchFallback": "https://www.youtube.com/results?search_query=IPO+mhanje+kay+Marathi+mahiti", "title": "IPO म्हणजे काय? अर्ज कसा करावा? मराठी", "channel": "CA Rachana Ranade Marathi"}
)

add(
    "bull-market", "Bull Market", "Investing",
    "A sustained financial market cycle characterized by rising asset prices, buoyant corporate earnings, investor optimism, and sustained economic expansion.",
    "वित्तीय बाजार का वह दौर जिसमें शेयरों की कीमतें लगातार बढ़ती हैं, निवेशकों में आशावाद होता है और अर्थव्यवस्था में तेज विस्तार दिखाई देता है।",
    "शेअर बाजारातील अशी तेजीची स्थिती ज्यामध्ये शेअर्सचे भाव सातत्याने वाढत असतात, गुंतवणूकदारांमध्ये प्रचंड उत्साह असतो आणि आर्थिक वाढ वेगाने होते.",
    "An ascending high tide that lifts nearly all vessels in the harbor while investor optimism runs high.",
    "The multi-year bull market in India following major structural economic reforms has witnessed the Nifty 50 compound aggressively over cyclical decades.",
    "Maintain emotional discipline during roaring bull markets; rebalance asset allocation periodically rather than abandoning risk management.",
    "तेजी के बाजार में जरूरत से ज्यादा उत्साहित होकर अपनी पूरी पूंजी एक ही जगह न झोंकें; रीबैलेंसिंग का पालन करें।",
    "बाजारात प्रचंड तेजी असताना हुरळून न जाता नियमितपणे नफा काढून योग्य विविधीकरण राखणे आवश्यक असते.",
    "Assuming every speculative micro-cap stock you bought during a bull run was due to your personal genius rather than the systemic rising tide.",
    "तेजी के दौर में खराब कंपनियों के शेयरों से मिले मुनाफे को अपनी व्यक्तिगत बुद्धिमत्ता मान लेना और जोखिम भरा जुआ खेलना।",
    "तेजीच्या लाटेत निकृष्ट शेअर्स वाढले तरी स्वतःला बाजाराचा तज्ज्ञ समजून अतिजोखीम पत्करणे.",
    "A bull market can continue ascending endlessly without any cyclical corrections or macro consolidations.",
    "बुल मार्केट कभी समाप्त नहीं होता और इसमें कभी भी 10%-20% की सामान्य गिरावट नहीं आ सकती।",
    "तेजीचा बाजार कधीच संपत नाही आणि त्यात कधीही मोठी घसरण होत नाही असा भ्रम.",
    ["Salaried Employees", "Students & Freshers"],
    {"searchFallback": "https://www.youtube.com/results?search_query=Bull+vs+Bear+market+cycles+explained+English", "title": "Surviving and Profiting in Bull Markets", "channel": "Zerodha Varsity"},
    {"searchFallback": "https://www.youtube.com/results?search_query=Bull+market+kya+hota+hai+Hindi", "title": "बुल मार्केट में क्या गलतियां न करें?", "channel": "Asset Yogi"},
    {"searchFallback": "https://www.youtube.com/results?search_query=Teji+mandee+bajar+Marathi", "title": "शेअर बाजारातील तेजी आणि मंदी मराठी", "channel": "Groww Marathi"}
)

add(
    "bear-market", "Bear Market", "Investing",
    "A protracted market decline where major stock indices drop by 20% or more from recent cyclical peaks, accompanied by widespread fear and pessimism.",
    "शेयर बाजार का वह मंदी का दौर जब प्रमुख सूचकांक अपने उच्चतम स्तर से 20% या उससे अधिक गिर जाते हैं और बाजार में निराशा का माहौल होता है।",
    "शेअर बाजारातील अशी मोठी मंदीची स्थिती ज्यामध्ये प्रमुख निर्देशांक आपल्या उच्चांकावरून २०% किंवा त्यापेक्षा जास्त घसरतात आणि भीतीचे वातावरण असते.",
    "A harsh winter season that clears dead underbrush, testing the resilience of your long-term financial shelter.",
    "Notable Indian bear markets occurred during the 2008 Global Financial Crisis (-50%+) and the March 2020 pandemic crash (-38%), followed by violent recoveries.",
    "Bear markets are wealth creation sales; disciplined investors who aggressively continue SIPs through bear cycles build generational wealth.",
    "मंदी का दौर वेल्थ क्रिएशन की सबसे बड़ी सेल (डिस्काउंट) होती है; इस समय SIP चालू रखने वाले ही भविष्य में अमीर बनते हैं।",
    "मंदीचा काळ म्हणजे सर्वोत्तम कंपन्यांचे शेअर्स स्वस्तात मिळण्याची सुवर्णसंधी; या काळात SIP सुरू ठेवणारेच मोठी संपत्ती कमावतात.",
    "Panic-selling quality equity portfolios at the absolute bottom of a bear market crash, locking in permanent capital losses.",
    "मंदी के चरम पर डरकर अपने बेहतरीन म्यूचुअल फंड और शेयर औने-पौने दाम पर बेच देना और वास्तविक नुकसान उठाना।",
    "घबराून बाजाराच्या तळाला उत्तम शेअर्स विकून कायमस्वरूपी आर्थिक नुकसान करून घेणे.",
    "A bear market crash means the entire national enterprise economy will permanently collapse to zero value.",
    "शेयर बाजार गिरने का मतलब है कि देश की पूरी अर्थव्यवस्था स्थायी रूप से बर्बाद हो चुकी है और अब कभी नहीं सुधरेगी।",
    "बाजार कोसळल्याने देशाची अर्थव्यवस्था पूर्णपणे नष्ट होणार आहे असा टोकाचा भीतीपोटी विचार करणे.",
    ["Salaried Employees", "Students & Freshers"],
    {"searchFallback": "https://www.youtube.com/results?search_query=How+to+invest+during+a+bear+market+crash+English", "title": "Bear Market Survival Guide for Investors", "channel": "Pranjal Kamra"},
    {"searchFallback": "https://www.youtube.com/results?search_query=Bear+market+me+kya+kare+Hindi", "title": "Bear Market में SIP चालू रखें या बंद करें?", "channel": "Labor Law Advisor"},
    {"searchFallback": "https://www.youtube.com/results?search_query=Mandi+madhe+guntavnuk+Marathi", "title": "मंदीच्या काळात गुंतवणूक कशी हाताळावी? मराठी", "channel": "CA Rachana Ranade Marathi"}
)

add(
    "real-return", "Real Return (Inflation-Adjusted Yield)", "Investing",
    "The true economic gain realized on an investment after subtracting the eroding effects of inflation and income taxation from the nominal yield.",
    "मुद्रास्फीति (महंगाई) और आयकर की कटौती के बाद किसी निवेश पर प्राप्त होने वाला वास्तविक शुद्ध लाभ।",
    "नाममात्र परताव्यामधून महागाईचा दर आणि देय कर वजा केल्यानंतर हातात उरणारा खराखुरा निव्वळ नफा.",
    "The actual speed a boat moves upstream against a strong counter-current of inflation.",
    "If a bank FD yields 7% nominal, taxation takes away 2.1% (30% slab), leaving 4.9%. If lifestyle inflation is 6%, your Real Return is negative (-1.1%).",
    "Always demand a positive post-tax real return from your long-term multi-decade retirement capital.",
    "अपने रिटायरमेंट पोर्टफोलियो का आकलन हमेशा महंगाई और टैक्स घटाने के बाद बचे 'Real Return' से ही करें।",
    "दीर्घकालीन बचतीचा विचार करताना नेहमी कर आणि महागाई वजा जाता मिळणाऱ्या खऱ्या परताव्याची (Real Return) खात्री करा.",
    "Celebrating a 7% nominal return on an investment while ignoring that the cost of living escalated by 8% over the exact same period.",
    "7% के नाममात्र रिटर्न पर खुश होना, जबकि उसी दौरान आवश्यक जीवनयापन खर्च 8% बढ़ चुका है।",
    "केवळ ७% चे व्याज मिळाले म्हणून आनंद मानणे, प्रत्यक्षात महागाई ८% ने वाढल्यामुळे भांडवलाचे मूल्य कमी झालेले असते.",
    "Nominal headline return and real inflation-adjusted return always yield the exact identical purchasing power value.",
    "हेडलाइन नाममात्र रिटर्न और महंगाई घटाकर बचा वास्तविक रिटर्न हमेशा एक समान क्रय शक्ति प्रदान करते हैं।",
    "नाममात्र परतावा आणि महागाई वजा जाता उरणारा परतावा हे दोन्ही पैशांची समान खरेदी क्षमता दर्शवतात.",
    ["Salaried Employees", "Freelancers & Creators", "Students & Freshers"],
    {"searchFallback": "https://www.youtube.com/results?search_query=Real+rate+of+return+inflation+adjusted+English", "title": "Nominal vs Real Rate of Return Explained", "channel": "Finnovate"},
    {"searchFallback": "https://www.youtube.com/results?search_query=Real+return+kya+hota+hai+Hindi", "title": "Real Return क्या है? महंगाई से पैसा कैसे बचाएं", "channel": "Asset Yogi"},
    {"searchFallback": "https://www.youtube.com/results?search_query=Khara+partava+real+return+Marathi", "title": "खरा परतावा (Real Return) कसा मोजावा? मराठी", "channel": "Groww Marathi"}
)

add(
    "liquidity", "Liquidity (Capital Accessibility)", "Investing",
    "The speed, ease, and efficiency with which an asset can be converted into ready cash without causing a material concession in its market price.",
    "किसी संपत्ति को उसके उचित बाजार मूल्य में बिना किसी बड़े नुकसान के कितनी जल्दी नकदी (Cash) में बदला जा सकता है, उसका पैमाना।",
    "कोणतीही मालमत्ता तिचे बाजारमूल्य न गमावता किती तत्परतेने आणि सहजतेने रोख पैशात रूपांतरित करता येते याचे प्रमाण.",
    "The ease of turning an ice cube in your freezer into drinkable water when you are thirsty.",
    "Savings bank deposits and overnight liquid mutual funds offer T+0/T+1 instant liquidity; physical real estate can take 6 to 18 months to liquidate.",
    "Maintain at least 6 months of living expenses in ultra-liquid accounts before committing surplus funds to illiquid property or startup investments.",
    "दीर्घकालिक अचल संपत्ति में पैसा लगाने से पहले कम से कम 6 महीने के खर्च के बराबर तरल (Liquid) आपातकालीन निधि रखें।",
    "दीर्घकालीन मालमत्तांमध्ये पैसे गुंतवण्यापूर्वी किमान ६ महिन्यांचा घरखर्च सहज उपलब्ध होणाऱ्या लिक्विड खात्यात ठेवावा.",
    "Locking up emergency reserve capital in illiquid agricultural land or long-lock-in endowment insurance policies.",
    "आपातकालीन पैसे को ऐसी जगह फंसा देना जहां से जरूरत पड़ने पर महीनों तक पैसा न निकाला जा सके।",
    "आणीबाणीच्या पैशांची अशी ठिकाणी गुंतवणूक करणे जिथून गरजेच्या वेळी तातडीने पैसे काढणे अशक्य असते.",
    "Physical land and real estate apartments in India can always be sold at full market value within 24 hours of an emergency.",
    "जरूरत पड़ने पर जमीन या मकान को 24 घंटे के भीतर पूरे बाजार भाव पर तुरंत नकदी में बदला जा सकता है।",
    "कोणतीही स्थावर मालमत्ता किंवा जमीन आणीबाणीच्या वेळी २४ तासांत पूर्ण भावात विकून लगेच रोख रक्कम मिळू शकते असा गैरसमज.",
    ["Salaried Employees", "Freelancers & Creators", "Startup Founders"],
    {"searchFallback": "https://www.youtube.com/results?search_query=Liquidity+in+investments+liquid+funds+English", "title": "Liquidity in Personal Finance: What Assets to Keep Liquid", "channel": "ClearTax"},
    {"searchFallback": "https://www.youtube.com/results?search_query=Liquidity+kya+hoti+hai+Hindi", "title": "Liquidity क्या है? इमरजेंसी में इसकी जरूरत क्यों?", "channel": "Labor Law Advisor"},
    {"searchFallback": "https://www.youtube.com/results?search_query=Taralta+liquidity+Marathi", "title": "तरलता (Liquidity) म्हणजे काय? मराठी माहिती", "channel": "Groww Marathi"}
)

add(
    "xirr", "XIRR (Extended Internal Rate of Return)", "Investing",
    "The accurate annualized return metric for investments characterized by irregular, recurring cash inflows and outflows on different historical dates.",
    "विभिन्न तारीखों पर किए गए कई निवेशों (जैसे मासिक SIP या आंशिक निकासी) का वास्तविक वार्षिक रिटर्न निकालने का सबसे सटीक गणितीय पैमाना।",
    "वेगवेगळ्या तारखांना केलेल्या गुंतवणुकीचा (उदा. मासिक SIP किंवा टप्प्याटप्प्याने पैसे काढणे) अचूक वार्षिक परतावा मोजणारे अधिकृत सूत्र.",
    "Evaluating the average speed of 60 individual train journeys started on 60 different monthly dates rather than measuring a single non-stop trip.",
    "Used universally across Zerodha Coin, Groww, INDmoney, and CAMS/KFintech statements to show the true performance of recurring SIP portfolios.",
    "Always evaluate recurring SIP portfolios using XIRR rather than simple point-to-point absolute return percentages.",
    "मासिक SIP का प्रदर्शन देखते समय हमेशा XIRR देखें, न कि केवल सामान्य कुल प्रतिशत मुनाफा।",
    "मासिक SIP चा खरा परतावा तपासण्यासाठी नेहमी XIRR पहावे, साधा टक्केवारी नफा नव्हे.",
    "Using simple point-to-point CAGR to judge a 5-year monthly SIP where each installment was invested for a completely different length of time.",
    "मासिक SIP के लिए साधारण CAGR का उपयोग करना, जबकि हर किस्त अलग-अलग समय तक बाजार में रही है।",
    "SIP चा परतावा मोजण्यासाठी साध्या CAGR चा चुकीचा वापर करणे.",
    "Simple CAGR and XIRR always calculate the exact identical percentage return on any recurring monthly SIP portfolio.",
    "मासिक SIP पोर्टफोलियो पर साधारण CAGR और XIRR हमेशा एक ही समान प्रतिशत संख्या दिखाते हैं।",
    "मासिक SIP पोर्टफोलिओसाठी साधा CAGR आणि XIRR हे दोन्ही नेहमी एकच आकडा दाखवतात.",
    ["Salaried Employees", "Students & Freshers", "Freelancers & Creators"],
    {"searchFallback": "https://www.youtube.com/results?search_query=CAGR+vs+XIRR+explained+mutual+funds+English", "title": "CAGR vs XIRR: How SIP Returns Are Truly Calculated", "channel": "Zerodha Varsity"},
    {"searchFallback": "https://www.youtube.com/results?search_query=XIRR+kya+hota+hai+Hindi+video", "title": "XIRR क्या होता है? SIP का सही रिटर्न कैसे निकालें", "channel": "Asset Yogi"},
    {"searchFallback": "https://www.youtube.com/results?search_query=XIRR+calculation+Marathi", "title": "XIRR म्हणजे काय? SIP परतावा मोजण्याची पद्धत मराठी", "channel": "CA Rachana Ranade Marathi"}
)

print(f"Investing terms added. Total now: {len(terms)}")
